<div class="topnav">
  <a class="active" href="#home">Home</a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=3"><img src="images/home.png" alt="home"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=4"><img src="images/explore.png" alt="explore"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=5"><img src="images/inbox.png" alt="inbox"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=6"><img src="images/profile.png" alt="profile"></a>
</div>