<div class="topnav">
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=3"><img src="images/home.png" alt="home"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=4"><img src="images/explore.png" alt="explore"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=5"><img src="images/inbox.png" alt="inbox"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=6"><img src="images/profile.png" alt="profile"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=8"><img src="images/editprofile.png" alt="edit profile"></a>
  <a href="http://142.31.53.220/~bigcypbigrosbigjosh/InstaRam/index.php?page=7"><img src="images/newpost.png" alt="new post"></a>
</div>