<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Rambook</title>

		<!-- include an external style sheet -->
		<link rel="stylesheet" href="style.css">  

		<!-- include an external JavaScript file -->
		<script src="script.js"></script>
	</head>
  
	<body onload="displayGrade()">

    <a href="?page=1">Page 1</a>
    <a href="?page=2">Page 2</a>
    <a href='?action=del'>Reset Everything</a>
   

	