
<div id="editLightbox" class="hidden">

	<div id="postnavEdit">	
		<span id="xEdit" onclick="toggleEdit()">&times;</span><br>
	</div>

	<div id="boundaryBigImageEdit">
		<img id="contentEdit" src="" alt="">
	</div>
	<form name="changeCaption" onsubmit="return editCaption()">
		<input type="textarea" name="postCaption" id="postCaption" value="">
		<input type="submit" value="Save">
	</form>

</div>