
<div id="termsofservice" class="hidden">
    <h1 id="toshead">
        Terms of Service
    </h1>
    <div class="terms"> 
        <p>
        Welcome to Ramstagram!<br>
        These Terms of Service (or “Terms”) govern your use of Ramstagram, except where we expressly state that separate terms (and not these) apply, and provide information 
        about the Ramstagram Experience (the Experience), outlined below. 
        When you create an Ramstagram account or use Ramstagram, you agree to these terms. 
        The Ramstagram Service is provided to you by BigCypBigRosBigJosh, Inc. These Terms of Service therefore constitute an agreement between you and BigCypBigRosBigJosh, Inc.
        </p><br>
        <h2>
        The Ramstagram Experience
        </h2 id="toshead2">
        <p> We agree to provide you the Ramstagram Experience, an all-inclusive personalized social media platform to bring you closer to your loved ones at Mount Doug. The Ramstagram Experience contains the following:</p>

        <p>Full, irrevocable ownership to your bank account, social security number, Phantom Wallet &copy;, and children.</p>

    </div>

    <button type="button" id="return" onclick="(changeVisibility('termsofservice'))">Return to Sign Up</button>
    <br>
</div>